---
title: "Slides"
number-sections: true
---


::: {.callout-note appearance="simple"}
Take a look at the [slides tutorial](https://kirenz.github.io/lab-toolkit/slides/slides.html#/title-slide) to learn how to use all slide options. 
:::



::: {.callout-tip collapse="true"}
## You have several options to start code development
1. **Colab**: Click on one of the links "💻 Jupyter Notebook" to start a Colab session. 
2. **Local**: Click on one of the links "💻 Jupyter Notebook" below, go to the Colab menu and choose "File" > "Download" > "Download .ipynb"
3. **Cloud Codespace**: Work in a fully configured dev environment in the cloud with a [GitHub Codespace VS Code Browser](/https://github.com/kirenz/lab-voice-to-text/blob/main/README.md) environment.
4. **Local VS Code with Codespace**: Use [GitHub Codespaces in your local Visual Studio Code environment](https://docs.github.com/en/codespaces/developing-in-codespaces/using-github-codespaces-in-visual-studio-code).
:::

For cost reasons we mainly use OpenAI's `gpt-3.5-turbo` model in our tutorials. However, you can simply replace `model="gpt-3.5-turbo"` with `model="gpt-4"` in the helper function. Note the [price difference](https://openai.com/pricing) between the two models.




## Voice to Text

Learn how to use Whisper to convert audio data into text data:

::: {.callout-tip appearance="simple" icon=false}

- [🖥️ Presentation](slides/voice-to-text.qmd)
- [💻 Jupyter Notebook](https://colab.research.google.com/github/kirenz/lab-voice-to-text/blob/main/code/voice-to-text.ipynb)
:::